version: '3.4'

services:

  sql_server:
    build: ./sqlServer
    ports:
      - "1433:1433"

  back_track_back_end:
    image: back_track_back_end
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sql_server
